[tools]
bun = "latest"

[tasks]
dev = "bun run --bun astro dev"
build = "bun run --bun astro build"
preview = "bun run --bun astro preview"
check = "bun run --bun --parallel check:astro check:svelte"
