[tools]
bun = "latest"
hk = "latest"
pkl = "latest"

[tasks]
dev = "bun run --bun astro dev"
build = "bun run --bun astro build"
preview = "bun run --bun astro preview"
check = "bun run --bun --parallel check:astro check:svelte check:biome check:knip"
fix = "bun run --bun --sequential fix:biome"

[env]
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"
